SF:lib\core\errors\exceptions.dart
DA:4,2
DA:9,1
DA:10,3
LF:3
LH:3
end_of_record
SF:lib\src\authentication\data\datasources\authentication_remote_data_source.dart
DA:19,1
DA:23,1
DA:33,2
DA:34,1
DA:35,2
DA:42,4
DA:43,1
DA:44,2
DA:46,1
DA:49,0
DA:53,0
DA:56,0
LF:12
LH:9
end_of_record
SF:lib\core\errors\failure.dart
DA:5,0
DA:13,0
DA:14,0
DA:18,0
DA:20,0
DA:21,0
DA:22,0
DA:23,0
LF:8
LH:0
end_of_record
SF:lib\src\authentication\data\models\user_model.dart
DA:7,0
DA:14,0
DA:15,0
DA:18,0
DA:20,0
DA:21,0
DA:27,0
DA:28,0
DA:29,0
DA:30,0
DA:31,0
DA:32,0
DA:35,0
DA:36,0
DA:37,0
DA:38,0
DA:39,0
DA:42,0
DA:48,0
DA:49,0
DA:50,0
DA:51,0
DA:52,0
LF:23
LH:0
end_of_record
SF:lib\src\authentication\domains\entities\user.dart
DA:4,0
DA:11,0
DA:12,0
DA:24,0
DA:25,0
LF:5
LH:0
end_of_record
